# Generated by Django 2.2.4 on 2019-08-29 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConceitoCulinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PassoTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('foto', models.BinaryField(null=True)),
                ('categorias', models.ManyToManyField(to='django_apptitoso.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeDeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=64)),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.BinaryField()),
                ('receitas_salvas', models.ManyToManyField(to='django_apptitoso.Receita')),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.Usuario'),
        ),
        migrations.CreateModel(
            name='Passo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
                ('ordem_passo', models.IntegerField()),
                ('foto', models.BinaryField(null=True)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.Receita')),
                ('timer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.PassoTimer')),
            ],
        ),
    ]
