# Generated by Django 2.2.4 on 2019-09-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CulinaryConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('picture', models.BinaryField(null=True)),
                ('categories', models.ManyToManyField(blank=True, to='django_apptitoso.Category')),
            ],
        ),
        migrations.CreateModel(
            name='StepTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('saved_recipes', models.ManyToManyField(blank=True, to='django_apptitoso.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('step_order', models.IntegerField()),
                ('picture', models.BinaryField(null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.Recipe')),
                ('timer', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.StepTimer')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.Recipe')),
                ('unit_of_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.UnitOfMeasurement')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.User'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(null=True)),
                ('evaluation_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.EvaluationCriteria')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.Recipe')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.User')),
            ],
        ),
    ]
