# Generated by Django 2.2.6 on 2019-11-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_apptitoso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culinaryconcept',
            name='picture',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.BinaryField(null=True),
        ),
    ]
