# Generated by Django 2.2.4 on 2019-08-29 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_apptitoso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoCriterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_criterio', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaIngrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.Receita')),
                ('unidade_de_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.UnidadeDeMedida')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(null=True)),
                ('criterio_de_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.AvaliacaoCriterio')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.Receita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.Usuario')),
            ],
        ),
    ]
