# Generated by Django 2.2.4 on 2019-09-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_apptitoso', '0002_auto_20190922_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culinaryconcept',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
