# Generated by Django 2.2.6 on 2019-11-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_apptitoso', '0002_auto_20191112_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culinaryconcept',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/culinaryConcept'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/recipe/picture'),
        ),
        migrations.AlterField(
            model_name='step',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/recipe/step'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/user'),
        ),
    ]
