# Generated by Django 2.2.4 on 2019-08-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_apptitoso', '0002_avaliacao_avaliacaocriterio_receitaingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceitoculinario',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
