# Generated by Django 2.2.6 on 2019-11-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_apptitoso', '0003_auto_20191113_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.User'),
        ),
    ]
