# Generated by Django 2.2.6 on 2019-11-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_apptitoso', '0005_auto_20191114_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='user_profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='django_apptitoso.User'),
            preserve_default=False,
        ),
    ]
